[package]
name = "stoa"
version = "0.1.0"
authors = ["lucas.abbruzzini@proton.me"]
edition = "2024"
license = "Apache 2.0"

[dependencies]
serde = { version = "1.0", features = ["derive"] }

[package.metadata.docs.rs]
all-features = true
